version: "3"
services:
  app:
    image: node:19-alpine
    working_dir: /app
    command: sh -c "npm install && npm run start"
    volumes:
      - ./dist:/app/dist
      - ./package.json:/app/package.json